name: Deploy to Development Environment
on:
  push:
    branches:
      - develop
jobs:
  lint-test:
    uses: ./.github/workflows/lint-test.yml
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Deploy to development Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './dist'
          production-branch: develop
          deploy-message: "Deployed from Github Actions"
        env: 
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DEV_SITE_ID }}
        timeout-minutes: 1
